clear all
close all
clc
exvivo=load("results_exvivo.mat");
lge=load("results_lge.mat");
mnm=load("results_mnm.mat");
variable={'gdsc_myo'};
% DSC_MYO exvivo
DSC_MYO_exvivo=[signrank(exvivo.B.gdsc_myo,exvivo.TA.gdsc_myo),...
    signrank(exvivo.B.gdsc_myo,exvivo.SA.gdsc_myo),...
    signrank(exvivo.B.gdsc_myo,exvivo.SATA.gdsc_myo)];

% HD_MYO exvivo
HD_MYO_exvivo=[signrank(exvivo.B.hd_myo,exvivo.TA.hd_myo),...
    signrank(exvivo.B.hd_myo,exvivo.SA.hd_myo),...
    signrank(exvivo.B.hd_myo,exvivo.SATA.hd_myo)];

%Cine
DSC_MYO_mnm=[signrank(mnm.B.gdsc_myo,mnm.TA.gdsc_myo),...
    signrank(mnm.B.gdsc_myo,mnm.SA.gdsc_myo),...
    signrank(mnm.B.gdsc_myo,mnm.SATA.gdsc_myo)];
HD_MYO_mnm=[signrank(mnm.B.hd_myo,mnm.TA.hd_myo),...
    signrank(mnm.B.hd_myo,mnm.SA.hd_myo),...
    signrank(mnm.B.hd_myo,mnm.SATA.hd_myo)];

DSC_lv_mnm=[signrank(mnm.B.gdsc_lv,mnm.TA.gdsc_lv),...
    signrank(mnm.B.gdsc_lv,mnm.SA.gdsc_lv),...
    signrank(mnm.B.gdsc_lv,mnm.SATA.gdsc_lv)];
HD_lv_mnm=[signrank(mnm.B.hd_lv,mnm.TA.hd_lv),...
    signrank(mnm.B.hd_lv,mnm.SA.hd_lv),...
    signrank(mnm.B.hd_lv,mnm.SATA.hd_lv)];

DSC_rv_mnm=[signrank(mnm.B.gdsc_rv,mnm.TA.gdsc_rv),...
    signrank(mnm.B.gdsc_rv,mnm.SA.gdsc_rv),...
    signrank(mnm.B.gdsc_rv,mnm.SATA.gdsc_rv)];
HD_rv_mnm=[signrank(mnm.B.hd_rv,mnm.TA.hd_rv),...
    signrank(mnm.B.hd_rv,mnm.SA.hd_rv),...
    signrank(mnm.B.hd_rv,mnm.SATA.hd_rv)];

%lge
DSC_MYO_lge=[signrank(lge.B.gdsc_myo,lge.TA.gdsc_myo),...
    signrank(lge.B.gdsc_myo,lge.SA.gdsc_myo),...
    signrank(lge.B.gdsc_myo,lge.SATA.gdsc_myo)];
HD_MYO_lge=[signrank(lge.B.hd_myo,lge.TA.hd_myo),...
    signrank(lge.B.hd_myo,lge.SA.hd_myo),...
    signrank(lge.B.hd_myo,lge.SATA.hd_myo)];

DSC_lv_lge=[signrank(lge.B.gdsc_lv,lge.TA.gdsc_lv),...
    signrank(lge.B.gdsc_lv,lge.SA.gdsc_lv),...
    signrank(lge.B.gdsc_lv,lge.SATA.gdsc_lv)];
HD_lv_lge=[signrank(lge.B.hd_lv,lge.TA.hd_lv),...
    signrank(lge.B.hd_lv,lge.SA.hd_lv),...
    signrank(lge.B.hd_lv,lge.SATA.hd_lv)];

DSC_mi_lge=[signrank(lge.B.gdsc_mi,lge.TA.gdsc_mi),...
    signrank(lge.B.gdsc_mi,lge.SA.gdsc_mi),...
    signrank(lge.B.gdsc_mi,lge.SATA.gdsc_mi)];
HD_mi_lge=[signrank(lge.B.hd_mi,lge.TA.hd_mi),...
    signrank(lge.B.hd_mi,lge.SA.hd_mi),...
    signrank(lge.B.hd_mi,lge.SATA.hd_mi)];